#!/bin/bash
# Before commiting to a branch, this makes sure the *last* commit
# was formatted for the changelog correctly.
npm run changelog-lint
exit_status=$?
if [ $exit_status -ne 0 ]; then
    source .githooks/show-changelog-hints.sh
fi
exit $exit_status
