#!/bin/bash
# Because commits are hard to remove (unless you are a pro at interactive
# rebasing), this commit hook script should make it easier for new
# contributors.

commit_msg=$1
cat "$commit_msg" | npm run changelog-lint-from-stdin
exit_status=$?

if [ $exit_status -ne 0 ]; then
    echo
    echo "--------------------------------------------------------------------"
    echo "The above output indicates a problem with the last commit message(s)."
    echo
    echo "The invalid message has not been saved."
    # echo "Type this to fix the message:"
    # echo "git commit -n --amend"
    echo
    echo "See:"
    echo "https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#writing-commit-messages"
    echo "--------------------------------------------------------------------"
    echo
fi


exit $exit_status
