version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    cooldown:
      default-days: 7
    groups:
      babel:
        patterns:
          - "@babel/*"
    ignore:
      # https://github.com/mozilla/web-ext/issues/3872
      - dependency-name: eslint
        versions:
          - ">= 10"
      - dependency-name: "@eslint/js"
        versions:
          - ">= 10"
      # https://github.com/mozilla/web-ext/issues/3883
      - dependency-name: yargs
        versions:
          - ">= 18"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      ssdlc-actions:
        patterns:
          - "mozilla/ssdlc-actions/*"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 99
