#!/usr/bin/env node

let COVERAGE = process.argv.includes('--coverage') || process.env.COVERAGE === 'y';

const {TRAVIS_OS_NAME} = process.env;
if (TRAVIS_OS_NAME === 'windows') {
  console.log(
    'Skipping coverage collection because running on',
    TRAVIS_OS_NAME,
    '(See issue https://github.com/mozilla/web-ext/issues/1739)'
  );
  COVERAGE = false;
}

const eslint = require('./lib/eslint');
const {flowCheck} = require('./lib/flow');
const {mochaUnit} = require('./lib/mocha');

console.log('Running eslint...');
if (!eslint()) {
  process.exit(1);
}

console.log('Running flow check...');
if (!flowCheck()) {
  process.exit(1);
}

console.log('Running mocha unit tests...', COVERAGE ? '(COVERAGE)' : '');
const ok = mochaUnit({}, COVERAGE);
process.exit(ok ? 0 : 1);
