name: ssdlc-sbom

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@5e1ea380f75b02891de776dcc00e74ad7cfeca9c # v1.3
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
