name: ssdlc-sbom

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@aa759c845c83060e2473fd8df60f9f408e34675d
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
