name: SSDLC Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

permissions: {}

jobs:
  code-security-analysis:
    permissions:
      security-events: write # required for uploading code scanning alerts
    uses: mozilla/ssdlc-actions/.github/workflows/code-security-analysis-public-repo.yml@507c5535545434e6892219c12d8d56a2b39bf710 # v1.1
